apiVersion: v1
kind: Template
metadata:
      name: wildfly-messaging-work-queue-worker
      annotations:
        iconClass: icon-jboss
        tags: wildfly, java, javaee, messaging, amqp
        template.openshift.io/provider-display-name: "Red Hat, Inc."
        description: This template creates a WildFly application receiving message from an AMQP broker and sending replies.
        tags: instant-app
parameters:
  - name: SOURCE_REPOSITORY_URL
    description: The source URL for the application
    displayName: Source URL
    value: 'https://github.com/dummy_org/dummy_repo'
    required: true
  - name: GITHUB_WEBHOOK_SECRET
    description: The secret used to configure a GitHub webhook
    displayName: GitHub Webhook Secret
    required: true
    from: '[a-zA-Z0-9]{40}'
    generate: expression
  - name: SOURCE_REPOSITORY_REF
    description: The branch name for the application
    displayName: Source Branch
    value: master
    required: true
  - name: SOURCE_REPOSITORY_DIR
    description: The location within the source repo of the application
    displayName: Source Directory
    value: .
    required: true
  - name: ARTIFACT_DIR
    description: "Directory from which archives will be copied into the deployment folder. If unspecified, all archives in /target will be copied."
    displayName: Artifacts Directory
    value: target
    required: false
  - name: CONTEXT_DIR
    description: "Path within Git project to build; empty for root project directory."
    displayName: Context Directory
    value: frontend
    required: false
objects:
  - kind: ImageStream
    apiVersion: image.openshift.io/v1
    metadata:
      name: wildfly-messaging-work-queue-worker
      creationTimestamp: null
      labels:
        app: wildfly-messaging-work-queue-worker
    spec:
      lookupPolicy:
        local: false
    status:
      dockerImageRepository: ''
  - kind: BuildConfig
    apiVersion: build.openshift.io/v1
    metadata:
      name: wildfly-messaging-work-queue-worker
      creationTimestamp: null
      labels:
        app: wildfly-messaging-work-queue-worker
    spec:
      triggers:
        - type: GitHub
          github:
            secret: '${GITHUB_WEBHOOK_SECRET}'
        - type: ConfigChange
        - type: ImageChange
          imageChange: {}
      source:
        type: Git
        git: {
          uri: '${SOURCE_REPOSITORY_URL}',
          ref: '${SOURCE_REPOSITORY_REF}'
        }
        contextDir: ${CONTEXT_DIR}
      strategy:
        type: Source
        sourceStrategy:
          from:
            kind: ImageStreamTag
            namespace: openshift
            name: 'wildfly:latest'
          incremental: true
          env: [
            {
              "name": "ARTIFACT_DIR", 
              "value": "${ARTIFACT_DIR}"
            }
          ]
      output:
        to:
          kind: ImageStreamTag
          name: 'wildfly-messaging-work-queue-worker:latest'
      resources: {}
      postCommit: {}
      nodeSelector: null
    status:
      lastVersion: 0
  - kind: DeploymentConfig
    apiVersion: apps.openshift.io/v1
    metadata:
      name: wildfly-messaging-work-queue-worker
      creationTimestamp: null
      labels:
        app: wildfly-messaging-work-queue-worker
    spec:
      strategy:
        resources: {}
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - wildfly-messaging-work-queue-worker
            from:
              kind: ImageStreamTag
              name: 'wildfly-messaging-work-queue-worker:latest'
      replicas: 1
      test: false
      selector:
        app: placeholder-app-label-d46881878f594a2dadfd963843452aab
        deploymentconfig: wildfly-messaging-work-queue-worker
      template:
        metadata:
          creationTimestamp: null
          labels:
            app: placeholder-app-label-d46881878f594a2dadfd963843452aab
            deploymentconfig: wildfly-messaging-work-queue-worker
        spec:
          containers:
            - name: wildfly-messaging-work-queue-worker
              image: 'wildfly-messaging-work-queue-worker:latest'
              ports:
                - containerPort: 8080
                  protocol: TCP
              resources:
                limits:
                  memory: 1G
              env: []
              readinessProbe:
                httpGet:
                  path: /health
                  port: 8080
                  scheme: HTTP
                initialDelaySeconds: 5
                timeoutSeconds: 3
                periodSeconds: 10
                failureThreshold: 10
              livenessProbe:
                httpGet:
                  path: /health
                  port: 8080
                  scheme: HTTP
                initialDelaySeconds: 60
                timeoutSeconds: 3
    status:
      latestVersion: 0
      observedGeneration: 0
      replicas: 0
      updatedReplicas: 0
      availableReplicas: 0
      unavailableReplicas: 0
  - kind: Service
    apiVersion: v1
    metadata:
      name: wildfly-messaging-work-queue-worker
      creationTimestamp: null
      labels:
        app: wildfly-messaging-work-queue-worker
    spec:
      ports:
        - name: 8080-tcp
          protocol: TCP
          port: 8080
          targetPort: 8080
      selector:
        app: placeholder-app-label-d46881878f594a2dadfd963843452aab
        deploymentconfig: wildfly-messaging-work-queue-worker
    status:
      loadBalancer: {}
  - apiVersion: v1
    kind: Route
    metadata:
      name: wildfly-messaging-work-queue-worker
      labels:
        app: wildfly-messaging-work-queue-worker
    spec:
      port:
        targetPort: 8080-tcp
      to:
        kind: Service
        name: wildfly-messaging-work-queue-worker
